travis:
  secure:
    BINSTAR_TOKEN: d4erXObLPYUQBa2UFjV9Tff+GbzmJhBfdbhmOz+r49HX/f8Z/obGxTlYuoqrzWK9huKs+30OecAcEMDvdh5Rf/UQWi3+fCuUdazEUT7ss3qc7zxFsjciqDztJwDi0OyT0807uzER0Wwvc0jyIR2f57ZFLgTzJCosHa/buVA0pC1/YGj6rsVbqFgGLHJgxsZvd9u7z+1ZVXc7/7CHXxYnZSAB3azoDyM4hetCKFq/+MQjmvaFIUReF4YOIaPCQHC0mqB9Vl6yAPxr4f06m7SWPNJerhUtFxBvU+nxOgnT3y8MC2VnKcfT5CDqEPBIOArtWnwc12UTKhLcujwmXQxp9RS/ZpdK0sDO5qgZ4zQeqOj5M1imdeL/htzFI9YlZ6OBtrrxfboP+hYcYiwHueDptx5ZMUhnkDmmZhtSkdHgFNSVLSX7HrBtfUZMhP6eJltGe1oaj9uVvZO/TLFl32LOjaLdOBoQNYIgfhvI1dkbKCK6OtSGV8sOm76BcA9QDzzCiso4XsWbrSyPN4HqON+lB7S4qVILhE07akOdi3mVAcY2yaQIrPRaQXdwN0S1ECT624f9V92CnVS9pGyFuAQDm+q4DVFUDYchmATLMObS9kc/y5q1YoRhXjJdKgmvUuNpyhvOLeCG2ivbXqm+bfT10Xuhjk+iZP6auT8E2PYIltw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
