travis:
  secure:
    BINSTAR_TOKEN: vWPBt8wZIy/qI4ieSWsYNgyOeZ2fCkxzaaLEwKV1mceClOD5bQAaNK4UVMnAuYrVbVxt5qxvjA0vTjvleSs+aAdHmI/XJGDcbaiTntBgcQsYLwDtHSJUNWYYbtVAviyA+yz3ydbg+U50bBlqH4yLdhYiIsFE9hLhuxJM8GKnhbUhZ4o9nhH35mhu7Xb+7s68fHAoTFeoo3s7evd/O4ckpxxiAtWXVATcEwJ2DUwAosAfrGvr45p1GPFNNXndcqTVQGQ6tzL71Q64SrBJRZ5m1/RVMBY4sDT9ehiIcEQE2linF4CVJGpabBaflaoIFXxmitfKuI1f3TNLX2IJ93ebdg+vv1D3ZHgXLkFu/+MI3cUOeDkezwWJ9GcEQEAl+D26jWteg4eK3DvEv7W8PxE5PKA8X9GcGue8LbMhmt+UGKaRjR9hXjVh4pJlPkCsFob41k6x3eqQqR+LcuDDExH44OMoBkpoU/6x4YLxm9CgbzqNEo/bOXSvZ8TM/hgBwif7jbsJk/isBFWa+SV/wdoo40s952DvloDctBRQJ/6XnXY3p3MVENDidFu5OYk4sLNQHsrOZPnzXNnHeEZnfWNiDvh7IhbmpeHzpuItNI+TjQMrumifuR7vNufxOF7gG4copj5FEaV+bgfA5++lDx0OWsBEfNZNg55MEUWuWbux9Vg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
