travis:
  secure:
    BINSTAR_TOKEN: vUXQmzUOgOB6JOu5qF+klEv9GvI5LZcIe6eG4UXcHbojR4i0H5KTB+5mbSJuwduOKgxm0nwVit3/OIkwIrWQBb6sOC3KAKP/pjHsil+ngrLOyi3k9v5KmGOTResx45ySZQpd5pC5btiD85/o0+1n96Pkx7AeFN+Ae8ymCWfxp3Xv+wp0X/0E0Ul8XhYAVqZi8mPyqdqSxfP1dbIMSxnN4hpsQhaf7KTWxLSFFkoFmSZc0OTilDvcLKEe2wzup03XRluKbeKENdxe0yZiX4zg4a2o3x2Sl3WpCIAtlU3FW7jWLShLrJT9w/ZOOPyW7K0dDpPdjcSil4en1f9DsLpo7VB7Hb+B6XJj4euFo4B4k1959oKsI7J2wp9rueGEvKCpJ2V1Qd9DWUTHkjxfr4Uw6VKUJuifJ2hL49NEI6eA0YeREIga7/sLI4kpaAbHZusxp4swjRR1Nq7cRiISuUIEW/ybQpT7v2ssKYVw9kop5Hlc+RUg+aGitXZMQsxuZ/pqUZEvRPAWSBHt3uIq9Tlyl4ADcCwMbQ6ZlD4NneK9HHLKDJ4RekriN2cyiXWqRl6ubWMK4WxgmmWPHzGQAFjG1yR6habyYLwNQGHYLAGItgcIfsH9b8M5TvxM3N47p1Ok9r/p9lp6BYn+zKW486SNI8KlJcnLcJMUcrqcCL89oso=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
